// Copy carried over from the first RemoTap site (assets/js/i18n.js).
export const BASE = {
 "en": {
  "meta.title": "RemoTap | NFC business cards & tap stands in Cairo",
  "nav.how": "How it works",
  "nav.pricing": "Pricing",
  "nav.demo": "Live demo",
  "nav.faq": "FAQ",
  "nav.order": "Order now",
  "lang.switch": "ع",
  "hero.eyebrow": "NFC cards & stands · Cairo & Giza",
  "hero.title1": "Your identity.",
  "hero.title2": "One tap away.",
  "hero.lead": "A card or stand that opens your contact page, InstaPay, WhatsApp and Google reviews the moment a phone touches it. No app. No typing. No reading your number out loud.",
  "hero.cta": "Order yours",
  "hero.cta2": "Try the live demo",
  "hero.note": "From <b>200 EGP</b> · Made to order in 4–7 days · Pay with InstaPay",
  "trust.1": "Works on iPhone & Android",
  "trust.2": "QR backup printed on every product",
  "trust.3": "Delivered in Cairo & Giza",
  "trust.4": "Change your links anytime, no reprint",
  "aud.eyebrow": "Who it's for",
  "aud.title": "Built for the counter and the campus",
  "aud.shop.tag": "For shops & cafés",
  "aud.shop.title": "Stop reading your InstaPay number out loud",
  "aud.shop.body": "Put a RemoTap stand next to the register. Customers tap and pay, follow you, or leave a review in seconds.",
  "aud.shop.t1": "InstaPay opens straight away, no typos, no wrong transfers",
  "aud.shop.t2": "Google reviews, WhatsApp and Instagram one tap away",
  "aud.shop.t3": "See how many customers tap every month",
  "aud.shop.cta": "Get a shop stand",
  "aud.stu.tag": "For students & freelancers",
  "aud.stu.title": "Share everything with one tap",
  "aud.stu.body": "Career fairs, events, first meetings. Tap your card on their phone and your whole profile is saved.",
  "aud.stu.t1": "LinkedIn, portfolio, Instagram and WhatsApp in one place",
  "aud.stu.t2": "“Save contact” adds you to their phone instantly",
  "aud.stu.t3": "Update your page anytime, the card never goes out of date",
  "aud.stu.cta": "Get a smart card",
  "how.eyebrow": "How it works",
  "how.title": "Ordered in 2 minutes. Tapping in a week.",
  "how.s1.t": "Order & pay",
  "how.s1.b": "Pick a card or stand, fill in your details, and pay with InstaPay.",
  "how.s2.t": "We build & print",
  "how.s2.b": "We design your page, print your product and test every tap before it ships.",
  "how.s3.t": "Tap & share",
  "how.s3.b": "It arrives in 4–7 days, ready to use. Need a change later? Just message us.",
  "price.eyebrow": "Pricing",
  "price.title": "One price. No monthly bills.",
  "price.lead": "Pay once. Plus includes your full RemoTap page free for the first year.",
  "price.tab.card": "Smart card",
  "price.tab.stand": "Shop stand",
  "price.basic": "Basic",
  "price.plus": "Plus",
  "price.badge": "Most chosen",
  "price.basic.sub.card": "A black NFC card that opens one link of your choice.",
  "price.plus.sub.card": "The card plus your own RemoTap page with all your links.",
  "price.basic.sub.stand": "A desk stand that opens your InstaPay directly.",
  "price.plus.sub.stand": "The stand plus a shop page: pay, review, follow and chat.",
  "price.once": "one-time",
  "price.note.basic": "Delivery fee added at checkout",
  "price.note.plus": "Includes 1 year of your page, then {renew} EGP/year",
  "f.hardware.card": "Premium black NFC card + QR backup",
  "f.hardware.stand": "Acrylic desk stand + QR backup",
  "f.onelink": "Opens one link (InstaPay, Instagram, LinkedIn…)",
  "f.page": "Your own branded RemoTap page",
  "f.alllinks": "All your links: InstaPay, WhatsApp, Google reviews, socials",
  "f.save": "“Save contact” button",
  "f.edits": "Free edits whenever you need them",
  "f.taps": "Monthly tap count",
  "price.choose": "Choose",
  "price.upsell": "Plus is only <b>200 EGP more</b> and turns one link into a full page.",
  "cmp.eyebrow": "Why switch",
  "cmp.title": "Paper runs out. A tap doesn't.",
  "cmp.h1": "",
  "cmp.h2": "Paper card / sign",
  "cmp.h3": "RemoTap",
  "cmp.r1": "Update your number or links",
  "cmp.r1a": "Reprint everything",
  "cmp.r1b": "Changed in minutes",
  "cmp.r2": "Customer copies InstaPay",
  "cmp.r2a": "Types it by hand",
  "cmp.r2b": "One tap",
  "cmp.r3": "Get Google reviews",
  "cmp.r3a": "Hope they remember",
  "cmp.r3b": "Review page opens instantly",
  "cmp.r4": "Know it's working",
  "cmp.r4a": "No idea",
  "cmp.r4b": "Monthly tap count",
  "cmp.r5": "Lasts",
  "cmp.r5a": "Until it's lost or thrown away",
  "cmp.r5b": "Years, one card",
  "demo.eyebrow": "Live demo",
  "demo.title": "This is what they see when they tap",
  "demo.lead": "A fast, clean page in Arabic or English. It opens in the phone's browser, so there's nothing to install.",
  "demo.p1.t": "Save contact",
  "demo.p1.b": "Adds your name, number and email to their phone in one tap.",
  "demo.p2.t": "Pay, chat, follow",
  "demo.p2.b": "InstaPay, WhatsApp, Instagram, LinkedIn and more. You choose the buttons.",
  "demo.p3.t": "Always up to date",
  "demo.p3.b": "New number? New Instagram? We update the page and your card keeps working.",
  "demo.cta": "Open the demo page",
  "faq.eyebrow": "Questions",
  "faq.title": "Good to know",
  "faq.q1": "Do people need an app to use it?",
  "faq.a1": "No. Modern iPhones and most Android phones read NFC automatically. They tap, and your page opens in the browser. Phones without NFC can scan the QR code printed on every product.",
  "faq.q2": "What if I change my number or links later?",
  "faq.a2": "With Plus, send us a message and we update your page. Your card or stand keeps working, with no reprint needed.",
  "faq.q3": "What happens after the first year of Plus?",
  "faq.a3": "You can renew for {renew} EGP/year. If you don't, your product keeps working and opens one main link of your choice.",
  "faq.q4": "How do I pay?",
  "faq.a4": "By InstaPay. After you place your order, you'll see the amount and our InstaPay details. Send the transfer screenshot on WhatsApp and we start printing.",
  "faq.q5": "How long does delivery take?",
  "faq.a5": "Every product is made to order in 4–7 days, then delivered by courier anywhere in Cairo and Giza.",
  "faq.q6": "Can I put my own logo or name on it?",
  "faq.a6": "Yes. Upload your logo or write the name you want printed when you order. We send you a preview before printing.",
  "cta.title": "Ready for your first tap?",
  "cta.lead": "Order in 2 minutes. Pay with InstaPay. Tapping within a week.",
  "cta.btn": "Order now",
  "cta.wa": "Ask us on WhatsApp",
  "foot.tag": "One tap. Endless connections.",
  "foot.rights": "© {year} RemoTap. Cairo, Egypt.",
  "sticky.from": "From",
  "wa.hello": "Hi RemoTap, I have a question about your cards and stands.",
  "o.title": "Order your RemoTap",
  "o.chat": "Prefer to order by chat?",
  "o.chat.btn": "Message us on WhatsApp",
  "o.chat.msg": "Hi RemoTap! I'd like to order a {product} ({plan}). Can you help me?",
  "o.stepof": "Step {n} of 4",
  "o.s1.t": "What would you like?",
  "o.s1.l": "Choose your product and plan. You can change it later.",
  "o.product": "Product",
  "o.card": "Smart card",
  "o.card.d": "Black NFC card for students, freelancers and staff",
  "o.stand": "Shop stand",
  "o.stand.d": "Desk stand for counters, cafés and salons",
  "o.plan": "Plan",
  "o.basic.d": "Opens one link",
  "o.plus.d": "Full page with all your links + 1 year included",
  "o.qty": "Quantity",
  "o.nudge": "For <b>200 EGP more</b>, Plus gives you a full page with all your links, free edits and tap stats.",
  "o.nudge.btn": "Switch to Plus",
  "o.s2.t": "What should it show?",
  "o.s2.l.basic": "Your product will open this one link.",
  "o.s2.l.plus": "Fill in what you want on your page. Leave empty what you don't need.",
  "o.pname": "Name on the page",
  "o.pname.ph.card": "e.g. RemoTap",
  "o.pname.ph.stand": "e.g. RemoTap Café",
  "o.ptitle": "Title or tagline",
  "o.ptitle.ph.card": "e.g. Smart NFC cards, Cairo",
  "o.ptitle.ph.stand": "e.g. Specialty coffee in Maadi",
  "o.print": "Text to print on the product",
  "o.print.ph": "Usually your name or shop name",
  "o.print.h": "We'll send you a preview before printing.",
  "o.logo": "Photo or logo",
  "o.logo.h": "JPG or PNG, up to 5 MB",
  "o.logo.pick": "Choose a file",
  "o.onelink": "The link it opens",
  "o.linktype": "Link type",
  "o.lt.instapay": "InstaPay",
  "o.lt.whatsapp": "WhatsApp",
  "o.lt.instagram": "Instagram",
  "o.lt.linkedin": "LinkedIn",
  "o.lt.facebook": "Facebook",
  "o.lt.tiktok": "TikTok",
  "o.lt.google": "Google reviews",
  "o.lt.website": "Website",
  "o.lt.menu": "Menu",
  "o.lt.email": "Email",
  "o.lt.phone": "Phone",
  "o.link.ph": "Paste the link, username or number",
  "o.links": "Your links",
  "o.pagelang": "Page language",
  "o.bio": "Short bio",
  "o.bio.ph": "One or two lines about you or your shop",
  "o.s3.t": "Where do we deliver?",
  "o.s3.l": "We deliver anywhere in Cairo and Giza.",
  "o.fullname": "Your full name",
  "o.phone": "Mobile / WhatsApp",
  "o.phone.ph": "01X XXXX XXXX",
  "o.email": "Email",
  "o.area": "Area",
  "o.cairo": "Cairo",
  "o.giza": "Giza",
  "o.address": "Full address",
  "o.address.ph": "Street, building, floor, apartment, landmark",
  "o.notes": "Notes",
  "o.notes.ph": "Anything we should know?",
  "o.optional": "(optional)",
  "o.s4.t": "Review your order",
  "o.s4.l": "Check everything, then place your order. You'll pay with InstaPay on the next screen.",
  "o.agree": "I understand the product is made to order and printing starts after payment.",
  "o.back": "Back",
  "o.next": "Continue",
  "o.place": "Place order",
  "o.placing": "Placing order…",
  "o.sum": "Your order",
  "o.sum.product": "Product",
  "o.sum.plan": "Plan",
  "o.sum.qty": "Quantity",
  "o.sum.sub": "Subtotal",
  "o.sum.delivery": "Delivery",
  "o.sum.total": "Total",
  "o.perk1": "Tested before it ships",
  "o.perk2": "Preview before printing",
  "o.perk3": "Made in 4–7 days",
  "o.req": "This field is required",
  "o.badphone": "Enter a valid Egyptian mobile number",
  "o.bademail": "Enter a valid email",
  "o.needlink": "Add at least one link",
  "o.needagree": "Please confirm to continue",
  "o.bigfile": "File is larger than 5 MB",
  "o.fail": "We couldn't save your order. Please send it to us on WhatsApp instead.",
  "p.title": "Order placed! Now complete your payment",
  "p.lead": "Your order number is",
  "p.amount": "Amount to transfer",
  "p.s1": "Send the amount with InstaPay",
  "p.s1.b": "Use this InstaPay address or number:",
  "p.open": "Open InstaPay",
  "p.copy": "Copy",
  "p.copied": "Copied",
  "p.s2": "Send us the transfer screenshot",
  "p.s2.b": "Tap the button, attach the screenshot, and send. We'll confirm and start printing.",
  "p.wa": "Send on WhatsApp",
  "p.s3": "Get your preview",
  "p.s3.b": "We'll send you a design preview on WhatsApp before printing.",
  "p.home": "Back to home",
  "p.wamsg": "Hi RemoTap! I placed order {id}.\nProduct: {product} ({plan}) × {qty}\nTotal: {total} EGP\nName: {name}\nI've attached my InstaPay transfer screenshot."
 },
 "ar": {
  "meta.title": "RemoTap | كروت وستاندات NFC في القاهرة",
  "nav.how": "إزاي بيشتغل",
  "nav.pricing": "الأسعار",
  "nav.demo": "جرّب بنفسك",
  "nav.faq": "أسئلة",
  "nav.order": "اطلب دلوقتي",
  "lang.switch": "EN",
  "hero.eyebrow": "كروت وستاندات NFC · القاهرة والجيزة",
  "hero.title1": "هويتك كلها",
  "hero.title2": "في لمسة واحدة",
  "hero.lead": "كارت أو ستاند بيفتح صفحتك، إنستاباي، واتساب وتقييمات جوجل أول ما الموبايل يلمسه. من غير أبلكيشن، ومن غير ما تكتب أو تملي رقمك لحد.",
  "hero.cta": "اطلب كارتك",
  "hero.cta2": "جرّب الديمو",
  "hero.note": "يبدأ من <b>200 جنيه</b> · بيتعمل مخصوص ليك في 4–7 أيام · الدفع بإنستاباي",
  "trust.1": "بيشتغل على آيفون وأندرويد",
  "trust.2": "QR احتياطي مطبوع على كل منتج",
  "trust.3": "توصيل للقاهرة والجيزة",
  "trust.4": "غيّر لينكاتك في أي وقت من غير طباعة",
  "aud.eyebrow": "لمين؟",
  "aud.title": "معمول للكاشير وللجامعة",
  "aud.shop.tag": "للمحلات والكافيهات",
  "aud.shop.title": "كفاية تملي رقم إنستاباي طول اليوم",
  "aud.shop.body": "حط ستاند RemoTap جنب الكاشير. الزبون يلمس ويدفع، أو يتابعك، أو يسيب تقييم في ثواني.",
  "aud.shop.t1": "إنستاباي يفتح على طول، من غير أخطاء ولا تحويلات غلط",
  "aud.shop.t2": "تقييمات جوجل وواتساب وإنستجرام على بعد لمسة",
  "aud.shop.t3": "اعرف كام زبون لمس الستاند كل شهر",
  "aud.shop.cta": "اطلب ستاند لمحلك",
  "aud.stu.tag": "للطلبة والفريلانسرز",
  "aud.stu.title": "شارك كل حاجة عنك بلمسة",
  "aud.stu.body": "معارض توظيف، إيفنتات، أول مقابلة. المس الموبايل بكارتك وبروفايلك كله يتحفظ عندهم.",
  "aud.stu.t1": "لينكدإن، البورتفوليو، إنستجرام وواتساب في مكان واحد",
  "aud.stu.t2": "زرار «احفظ الرقم» يضيفك لموبايلهم فورًا",
  "aud.stu.t3": "حدّث صفحتك في أي وقت، والكارت عمره ما يقدم",
  "aud.stu.cta": "اطلب كارتك الذكي",
  "how.eyebrow": "إزاي بيشتغل",
  "how.title": "تطلب في دقيقتين، وتستخدمه في أسبوع",
  "how.s1.t": "اطلب وادفع",
  "how.s1.b": "اختار كارت أو ستاند، اكتب بياناتك، وادفع بإنستاباي.",
  "how.s2.t": "إحنا نصمم ونطبع",
  "how.s2.b": "بنصمم صفحتك، نطبع المنتج، ونجرّب كل لمسة قبل ما نشحنه.",
  "how.s3.t": "المس وشارك",
  "how.s3.b": "بيوصلك في 4–7 أيام جاهز للاستخدام. عايز تغيّر حاجة بعدين؟ ابعتلنا بس.",
  "price.eyebrow": "الأسعار",
  "price.title": "سعر واحد، من غير اشتراك شهري",
  "price.lead": "بتدفع مرة واحدة. باقة Plus فيها صفحة RemoTap كاملة ببلاش أول سنة.",
  "price.tab.card": "كارت ذكي",
  "price.tab.stand": "ستاند للمحل",
  "price.basic": "Basic",
  "price.plus": "Plus",
  "price.badge": "الأكثر طلبًا",
  "price.basic.sub.card": "كارت NFC أسود بيفتح لينك واحد تختاره.",
  "price.plus.sub.card": "الكارت + صفحة RemoTap خاصة بيك فيها كل لينكاتك.",
  "price.basic.sub.stand": "ستاند مكتب بيفتح إنستاباي بتاعك على طول.",
  "price.plus.sub.stand": "الستاند + صفحة للمحل: دفع، تقييم، متابعة وشات.",
  "price.once": "مرة واحدة",
  "price.note.basic": "مصاريف التوصيل بتتضاف عند الطلب",
  "price.note.plus": "شامل سنة للصفحة، وبعدها {renew} جنيه في السنة",
  "f.hardware.card": "كارت NFC أسود فاخر + QR احتياطي",
  "f.hardware.stand": "ستاند أكريليك للمكتب + QR احتياطي",
  "f.onelink": "بيفتح لينك واحد (إنستاباي، إنستجرام، لينكدإن…)",
  "f.page": "صفحة RemoTap باسمك وشكلك",
  "f.alllinks": "كل لينكاتك: إنستاباي، واتساب، تقييمات جوجل، السوشيال",
  "f.save": "زرار «احفظ الرقم»",
  "f.edits": "تعديلات ببلاش وقت ما تحتاج",
  "f.taps": "عدد اللمسات كل شهر",
  "price.choose": "اختار",
  "price.upsell": "Plus بـ<b>200 جنيه زيادة بس</b> وبتحوّل اللينك الواحد لصفحة كاملة.",
  "cmp.eyebrow": "ليه تغيّر؟",
  "cmp.title": "الورق بيخلص، اللمسة لأ",
  "cmp.h1": "",
  "cmp.h2": "كارت أو لافتة ورق",
  "cmp.h3": "RemoTap",
  "cmp.r1": "تغيير رقمك أو لينكاتك",
  "cmp.r1a": "تطبع كل حاجة من الأول",
  "cmp.r1b": "يتغيّر في دقايق",
  "cmp.r2": "الزبون ياخد رقم إنستاباي",
  "cmp.r2a": "يكتبه بإيده",
  "cmp.r2b": "لمسة واحدة",
  "cmp.r3": "تجيب تقييمات جوجل",
  "cmp.r3a": "تتمنى يفتكر",
  "cmp.r3b": "صفحة التقييم تفتح فورًا",
  "cmp.r4": "تعرف إنه شغال",
  "cmp.r4a": "ولا فكرة",
  "cmp.r4b": "عدد اللمسات كل شهر",
  "cmp.r5": "يعيش",
  "cmp.r5a": "لحد ما يضيع أو يترمي",
  "cmp.r5b": "سنين، بكارت واحد",
  "demo.eyebrow": "جرّب بنفسك",
  "demo.title": "ده اللي بيشوفوه لما يلمسوا",
  "demo.lead": "صفحة سريعة ونضيفة بالعربي أو الإنجليزي. بتفتح في المتصفح، يعني مفيش حاجة تتنزّل.",
  "demo.p1.t": "احفظ الرقم",
  "demo.p1.b": "اسمك ورقمك وإيميلك يتسجلوا في موبايلهم بلمسة.",
  "demo.p2.t": "ادفع، كلّم، تابع",
  "demo.p2.b": "إنستاباي، واتساب، إنستجرام، لينكدإن وغيرهم. إنت اللي تختار الزراير.",
  "demo.p3.t": "دايمًا محدّثة",
  "demo.p3.b": "رقم جديد؟ إنستجرام جديد؟ بنحدّث الصفحة وكارتك يفضل شغال.",
  "demo.cta": "افتح صفحة الديمو",
  "faq.eyebrow": "أسئلة",
  "faq.title": "حاجات مهم تعرفها",
  "faq.q1": "محتاجين أبلكيشن عشان يستخدموه؟",
  "faq.a1": "لأ. الآيفون الحديث ومعظم موبايلات أندرويد بتقرا NFC لوحدها. يلمسوا، وصفحتك تفتح في المتصفح. والموبايلات اللي مفيهاش NFC تقدر تعمل سكان للـQR المطبوع على كل منتج.",
  "faq.q2": "لو غيّرت رقمي أو لينكاتي بعدين؟",
  "faq.a2": "مع Plus ابعتلنا رسالة ونحدّث صفحتك. الكارت أو الستاند يفضل شغال من غير ما تطبع تاني.",
  "faq.q3": "إيه اللي يحصل بعد أول سنة في Plus؟",
  "faq.a3": "تقدر تجدد بـ{renew} جنيه في السنة. ولو ما جددتش، المنتج يفضل شغال ويفتح لينك واحد رئيسي تختاره.",
  "faq.q4": "أدفع إزاي؟",
  "faq.a4": "بإنستاباي. بعد ما تطلب هتلاقي المبلغ وبيانات إنستاباي بتاعتنا. ابعت صورة التحويل على واتساب ونبدأ الطباعة.",
  "faq.q5": "التوصيل بياخد قد إيه؟",
  "faq.a5": "كل منتج بيتعمل مخصوص في 4–7 أيام، وبعدها بيتوصل بالكورير لأي مكان في القاهرة والجيزة.",
  "faq.q6": "ينفع أحط اللوجو أو اسمي عليه؟",
  "faq.a6": "أيوه. ارفع اللوجو أو اكتب الاسم اللي عايزه يتطبع وإنت بتطلب. وهنبعتلك شكله قبل الطباعة.",
  "cta.title": "جاهز لأول لمسة؟",
  "cta.lead": "اطلب في دقيقتين. ادفع بإنستاباي. وابدأ تستخدمه في أسبوع.",
  "cta.btn": "اطلب دلوقتي",
  "cta.wa": "اسألنا على واتساب",
  "foot.tag": "لمسة واحدة. تواصل بلا حدود.",
  "foot.rights": "© {year} RemoTap. القاهرة، مصر.",
  "sticky.from": "يبدأ من",
  "wa.hello": "أهلًا RemoTap، عندي سؤال عن الكروت والستاندات.",
  "o.title": "اطلب RemoTap بتاعك",
  "o.chat": "تحب تطلب بالشات؟",
  "o.chat.btn": "كلّمنا على واتساب",
  "o.chat.msg": "أهلًا RemoTap! عايز أطلب {product} ({plan}). ممكن تساعدني؟",
  "o.stepof": "خطوة {n} من 4",
  "o.s1.t": "عايز إيه؟",
  "o.s1.l": "اختار المنتج والباقة. تقدر تغيّرهم بعدين.",
  "o.product": "المنتج",
  "o.card": "كارت ذكي",
  "o.card.d": "كارت NFC أسود للطلبة والفريلانسرز والموظفين",
  "o.stand": "ستاند للمحل",
  "o.stand.d": "ستاند مكتب للكاشير والكافيهات والصالونات",
  "o.plan": "الباقة",
  "o.basic.d": "بيفتح لينك واحد",
  "o.plus.d": "صفحة كاملة بكل لينكاتك + سنة مجانًا",
  "o.qty": "الكمية",
  "o.nudge": "بـ<b>200 جنيه زيادة</b>، Plus بيديك صفحة كاملة بكل لينكاتك وتعديلات ببلاش وإحصائيات اللمس.",
  "o.nudge.btn": "حوّل لـ Plus",
  "o.s2.t": "يعرض إيه؟",
  "o.s2.l.basic": "منتجك هيفتح اللينك ده.",
  "o.s2.l.plus": "اكتب اللي عايزه في صفحتك. سيب فاضي اللي مش محتاجه.",
  "o.pname": "الاسم على الصفحة",
  "o.pname.ph.card": "مثلًا: RemoTap",
  "o.pname.ph.stand": "مثلًا: كافيه RemoTap",
  "o.ptitle": "الوظيفة أو جملة تعريفية",
  "o.ptitle.ph.card": "مثلًا: كروت وستاندات NFC ذكية، القاهرة",
  "o.ptitle.ph.stand": "مثلًا: قهوة مختصة في المعادي",
  "o.print": "الكلام اللي يتطبع على المنتج",
  "o.print.ph": "غالبًا اسمك أو اسم المحل",
  "o.print.h": "هنبعتلك شكله قبل الطباعة.",
  "o.logo": "صورة أو لوجو",
  "o.logo.h": "JPG أو PNG لحد 5 ميجا",
  "o.logo.pick": "اختار ملف",
  "o.onelink": "اللينك اللي هيفتحه",
  "o.linktype": "نوع اللينك",
  "o.lt.instapay": "إنستاباي",
  "o.lt.whatsapp": "واتساب",
  "o.lt.instagram": "إنستجرام",
  "o.lt.linkedin": "لينكدإن",
  "o.lt.facebook": "فيسبوك",
  "o.lt.tiktok": "تيك توك",
  "o.lt.google": "تقييمات جوجل",
  "o.lt.website": "موقع إلكتروني",
  "o.lt.menu": "المنيو",
  "o.lt.email": "إيميل",
  "o.lt.phone": "رقم تليفون",
  "o.link.ph": "حط اللينك أو اليوزر أو الرقم",
  "o.links": "لينكاتك",
  "o.pagelang": "لغة الصفحة",
  "o.bio": "نبذة قصيرة",
  "o.bio.ph": "سطر أو اتنين عنك أو عن محلك",
  "o.s3.t": "نوصّل فين؟",
  "o.s3.l": "بنوصّل لأي مكان في القاهرة والجيزة.",
  "o.fullname": "اسمك بالكامل",
  "o.phone": "الموبايل / واتساب",
  "o.phone.ph": "01X XXXX XXXX",
  "o.email": "الإيميل",
  "o.area": "المحافظة",
  "o.cairo": "القاهرة",
  "o.giza": "الجيزة",
  "o.address": "العنوان بالتفصيل",
  "o.address.ph": "الشارع، العمارة، الدور، الشقة، علامة مميزة",
  "o.notes": "ملاحظات",
  "o.notes.ph": "في حاجة عايزنا نعرفها؟",
  "o.optional": "(اختياري)",
  "o.s4.t": "راجع طلبك",
  "o.s4.l": "اتأكد من كل حاجة، وبعدين أكّد الطلب. هتدفع بإنستاباي في الخطوة الجاية.",
  "o.agree": "فاهم إن المنتج بيتعمل مخصوص والطباعة بتبدأ بعد الدفع.",
  "o.back": "رجوع",
  "o.next": "كمّل",
  "o.place": "أكّد الطلب",
  "o.placing": "بنسجّل طلبك…",
  "o.sum": "طلبك",
  "o.sum.product": "المنتج",
  "o.sum.plan": "الباقة",
  "o.sum.qty": "الكمية",
  "o.sum.sub": "المجموع",
  "o.sum.delivery": "التوصيل",
  "o.sum.total": "الإجمالي",
  "o.perk1": "بنجرّبه قبل الشحن",
  "o.perk2": "تشوف التصميم قبل الطباعة",
  "o.perk3": "جاهز في 4–7 أيام",
  "o.req": "الخانة دي مطلوبة",
  "o.badphone": "اكتب رقم موبايل مصري صحيح",
  "o.bademail": "اكتب إيميل صحيح",
  "o.needlink": "ضيف لينك واحد على الأقل",
  "o.needagree": "أكّد عشان تكمّل",
  "o.bigfile": "الملف أكبر من 5 ميجا",
  "o.fail": "ما قدرناش نسجّل طلبك. ابعتهولنا على واتساب لو سمحت.",
  "p.title": "طلبك اتسجّل! فاضل الدفع",
  "p.lead": "رقم طلبك",
  "p.amount": "المبلغ المطلوب تحويله",
  "p.s1": "حوّل المبلغ بإنستاباي",
  "p.s1.b": "استخدم عنوان أو رقم إنستاباي ده:",
  "p.open": "افتح إنستاباي",
  "p.copy": "نسخ",
  "p.copied": "اتنسخ",
  "p.s2": "ابعتلنا صورة التحويل",
  "p.s2.b": "دوس على الزرار، ارفق صورة التحويل وابعت. هنأكّد ونبدأ الطباعة.",
  "p.wa": "ابعت على واتساب",
  "p.s3": "استلم شكل التصميم",
  "p.s3.b": "هنبعتلك التصميم على واتساب قبل الطباعة.",
  "p.home": "الرجوع للرئيسية",
  "p.wamsg": "أهلًا RemoTap! عملت طلب رقم {id}.\nالمنتج: {product} ({plan}) × {qty}\nالإجمالي: {total} جنيه\nالاسم: {name}\nمرفق صورة تحويل إنستاباي."
 }
} as const;
