import { BASE } from "./dict-base";

/* New copy for the store (cart, product pages, landing). Old copy lives in dict-base.ts. */
const EXTRA = {
  en: {
    "meta.title": "RemoTap | NFC cards & tap stands store, Cairo",
    "prod.instapay": "InstaPay Tap Card",
    "hero.new": "New: the InstaPay tap card",
    "st.eyebrow": "Tap stands",
    "st.title": "A stand for every counter",
    "st.lead": "Square acrylic stands with an NFC chip and a QR code. Pick a ready design, {price} EGP each. Colours, text and logo are all yours to change.",
    "tag.custom": "Fully customizable",
    "tag.custom.short": "Customizable",
    "prod.style": "Stand design",
    "prod.style.note": "Fully customizable: send us your logo, colours and text on WhatsApp and we'll send a print preview before we make it.",
    "o.lt.vfcash": "Vodafone Cash",
    "o.lt.resume": "Resume / CV",
    "prod.instapay.short": "Customers tap their phone on it and your InstaPay payment opens. No typing your number, no wrong transfers.",
    "price.basic.sub.instapay": "A tap card that opens your InstaPay payment link.",
    "price.tab.instapay": "InstaPay card",
    "o.instapay": "InstaPay card",
    "o.instapay.d": "Opens your InstaPay payment link",
    "f.hardware.instapay": "Purple NFC tap card + QR backup",
    "f.instapay.direct": "One tap opens your InstaPay payment",
    "f.instapay.noapp": "Works on iPhone & Android, nothing to install",
    "f.instapay.change": "Changed your InstaPay? We update it, no reprint",
    "o.lt.instapay.ph": "Your InstaPay link (ipn.eg/…) or yourname@instapay",
    "tag.one": "One price",
    "ip.tap": "Tap your phone here",
    "ip.scan": "Scan to pay",
    "pick.eyebrow": "Not sure?",
    "pick.title": "What do you need it for?",
    "pick.lead": "Pick one and we'll show you the right product.",
    "pick.shop": "Customers pay me",
    "pick.shop.d": "Cafés, salons, shops, delivery",
    "pick.review": "My shop needs reviews & followers",
    "pick.review.d": "Counter stand with all your links",
    "pick.me": "Share my contact",
    "pick.me.d": "Students, freelancers, staff",
    "pick.why.instapay": "The InstaPay card is the quickest way to get paid: customers tap and your payment opens.",
    "pick.why.stand": "The Plus stand sits on your counter: pay, Google review, Instagram and WhatsApp in one tap.",
    "pick.why.card": "The Plus card opens your own page: save contact, LinkedIn, WhatsApp and more.",
    "pick.see": "See details",
    "plan.help": "Basic opens one link. Plus opens your own page with all your links, and you can change them anytime.",
    "prod.delfee": "Delivery {fee} EGP · Cairo & Giza · 4–7 days",
    "o.step.1": "Cart",
    "o.step.2": "Details",
    "o.step.3": "Delivery",
    "o.step.4": "Review",
    "o.total.mobile": "Total",
    "o.edit": "Edit",
    "faq.q7": "What is the InstaPay tap card?",
    "faq.a7": "A card-sized NFC tag for your counter, wallet or delivery bag. Customers tap their phone on it and your InstaPay payment link opens, so they never type your number. A QR code on the card works for phones without NFC.",
    "nav.shop": "Shop",
    "nav.cart": "Cart",
    "mq.1": "Made to order in 4–7 days",
    "mq.2": "Delivered in Cairo & Giza",
    "mq.3": "Pay with InstaPay",
    "mq.4": "Works on iPhone & Android",
    "mq.5": "QR backup on every product",
    "mq.6": "Change your links anytime",
    "hero.big1": "Tap.",
    "hero.big2": "Connect.",
    "hero.big3": "Grow.",
    "hero.store": "The NFC store for Cairo & Giza",
    "hero.shop": "Shop now",
    "hero.hint.mouse": "Hover to flip · Click to change the look",
    "hero.hint.touch": "Tap the card to flip it",
    "hero.scroll": "Scroll",
    "shop.eyebrow": "The lineup",
    "shop.title": "Pick your tap",
    "shop.lead": "A card for you, a stand for your counter, a card that gets you paid. Pay once, tap for years.",
    "shop.all": "All",
    "shop.cards": "Cards",
    "shop.stands": "Stands",
    "shop.view": "View",
    "shop.from": "From",
    "shop.page": "Full shop",
    "tag.new": "New",
    "tag.best": "Most chosen",
    "prod.card": "RemoTap Card",
    "prod.stand": "RemoTap Stand",
    "prod.card.short": "Black NFC card that shares your page with one tap.",
    "prod.stand.short": "Counter stand: customers tap to pay, follow or review.",
    "prod.plan": "Plan",
    "prod.qty": "Quantity",
    "prod.design": "Card look",
    "prod.design.note": "Pick the look you like. We send you the final print design on WhatsApp before printing.",
    "prod.flip": "Flip card",
    "prod.shuffle": "Next look",
    "prod.get": "What you get",
    "prod.delivery": "Delivery & payment",
    "prod.delivery.b": "Made to order in 4–7 days and delivered anywhere in Cairo & Giza. Courier fee is added at checkout. Pay with InstaPay after you order.",
    "prod.back": "All products",
    "prod.other": "You might also like",
    "stand.tap": "Tap to pay",
    "stand.scan": "or scan",
    "cart.title": "Your cart",
    "cart.empty": "Your cart is empty.",
    "cart.empty.cta": "Browse the shop",
    "cart.add": "Add to cart",
    "cart.added": "Added to cart",
    "cart.buy": "Buy now",
    "cart.remove": "Remove",
    "cart.sub": "Subtotal",
    "cart.delnote": "Courier fee is added at checkout.",
    "cart.checkout": "Checkout",
    "cart.keep": "Keep shopping",
    "cart.count": "{n} items",
    "o.s1.t": "Your cart",
    "o.s1.l": "Check your products. You can add another one or change the quantity.",
    "o.addmore": "Add another product",
    "o.empty": "Your cart is empty. Add a product to continue.",
    "o.oneperorder": "All products in this order open the same page.",
    "o.design": "Look",
    "p.items": "Items",
    "p.wamsg2": "Hi RemoTap! I placed order {id}.\n{items}\nTotal: {total} EGP\nName: {name}\nI've attached my InstaPay transfer screenshot.",
    "foot.shop": "Shop",
    "foot.help": "Help",
    "foot.follow": "Say hi",
    "foot.drops": "Get new drops and offers on WhatsApp",
    "foot.drops.btn": "Join on WhatsApp",
    "foot.drops.msg": "Hi RemoTap! Add me to your updates list.",
    "demo.phone.save": "Save contact",
    "demo.phone.resume": "View my resume",
    "big.1": "No app.",
    "big.2": "No typing.",
    "big.3": "Just tap.",
  },
  ar: {
    "meta.title": "RemoTap | متجر كروت NFC وستاندات اللمس في القاهرة",
    "prod.instapay": "كارت إنستاباي باللمس",
    "hero.new": "جديد: كارت إنستاباي باللمس",
    "st.eyebrow": "ستاندات اللمس",
    "st.title": "ستاند لكل كاشير",
    "st.lead": "ستاندات أكريليك مربعة فيها شريحة NFC وكود QR. اختار تصميم جاهز، كل واحد بـ {price} جنيه. الألوان والكلام واللوجو كلهم تقدر تغيّرهم.",
    "tag.custom": "قابل للتخصيص بالكامل",
    "tag.custom.short": "قابل للتخصيص",
    "prod.style": "تصميم الستاند",
    "prod.style.note": "قابل للتخصيص بالكامل: ابعتلنا اللوجو والألوان والكلام على واتساب وهنبعتلك شكل الطباعة قبل ما نصنعه.",
    "o.lt.vfcash": "فودافون كاش",
    "o.lt.resume": "السيرة الذاتية (CV)",
    "prod.instapay.short": "العميل يلمس الكارت بموبايله ويفتحله الدفع على إنستاباي بتاعك. من غير ما يكتب رقمك ومن غير تحويلات غلط.",
    "price.basic.sub.instapay": "كارت باللمس بيفتح لينك الدفع بتاعك على إنستاباي.",
    "price.tab.instapay": "كارت إنستاباي",
    "o.instapay": "كارت إنستاباي",
    "o.instapay.d": "بيفتح لينك الدفع على إنستاباي",
    "f.hardware.instapay": "كارت NFC بنفسجي + QR احتياطي",
    "f.instapay.direct": "لمسة واحدة تفتح الدفع على إنستاباي",
    "f.instapay.noapp": "شغال على آيفون وأندرويد من غير أي أبلكيشن",
    "f.instapay.change": "غيّرت إنستاباي؟ بنحدّثه من غير طباعة جديدة",
    "o.lt.instapay.ph": "لينك إنستاباي (ipn.eg/…) أو yourname@instapay",
    "tag.one": "سعر واحد",
    "ip.tap": "المس بموبايلك هنا",
    "ip.scan": "امسح وادفع",
    "pick.eyebrow": "مش متأكد؟",
    "pick.title": "محتاجه في إيه؟",
    "pick.lead": "اختار واحدة وهنوريك المنتج المناسب.",
    "pick.shop": "العملاء يدفعولي",
    "pick.shop.d": "كافيهات، صالونات، محلات، دليفري",
    "pick.review": "محلي محتاج تقييمات ومتابعين",
    "pick.review.d": "ستاند للكاشير بكل لينكاتك",
    "pick.me": "أشارك بياناتي",
    "pick.me.d": "طلبة، فريلانسرز، موظفين",
    "pick.why.instapay": "كارت إنستاباي أسرع طريقة تستلم فلوسك: العميل يلمس ويفتحله الدفع.",
    "pick.why.stand": "ستاند Plus على الكاشير: دفع، تقييم جوجل، إنستجرام وواتساب بلمسة.",
    "pick.why.card": "كارت Plus بيفتح صفحتك: احفظ الرقم، لينكدإن، واتساب وأكتر.",
    "pick.see": "شوف التفاصيل",
    "plan.help": "Basic بيفتح لينك واحد. Plus بيفتح صفحتك بكل لينكاتك وتقدر تغيّرها في أي وقت.",
    "prod.delfee": "التوصيل {fee} جنيه · القاهرة والجيزة · ٤–٧ أيام",
    "o.step.1": "السلة",
    "o.step.2": "البيانات",
    "o.step.3": "التوصيل",
    "o.step.4": "المراجعة",
    "o.total.mobile": "الإجمالي",
    "o.edit": "تعديل",
    "faq.q7": "يعني إيه كارت إنستاباي باللمس؟",
    "faq.a7": "كارت صغير بشريحة NFC تحطه على الكاشير أو في المحفظة أو شنطة الدليفري. العميل يلمسه بموبايله ويفتحله لينك الدفع بتاعك على إنستاباي، فمش محتاج يكتب رقمك. وفيه QR للموبايلات اللي مفيهاش NFC.",
    "nav.shop": "المتجر",
    "nav.cart": "السلة",
    "mq.1": "بنصنعه مخصوص في ٤–٧ أيام",
    "mq.2": "توصيل القاهرة والجيزة",
    "mq.3": "ادفع بإنستاباي",
    "mq.4": "شغال على آيفون وأندرويد",
    "mq.5": "QR احتياطي على كل منتج",
    "mq.6": "غيّر لينكاتك في أي وقت",
    "hero.big1": "المس.",
    "hero.big2": "اتواصل.",
    "hero.big3": "اكبر.",
    "hero.store": "متجر NFC للقاهرة والجيزة",
    "hero.shop": "تسوّق دلوقتي",
    "hero.hint.mouse": "عدّي عليه يتقلب · اضغط يغيّر الشكل",
    "hero.hint.touch": "المس الكارت عشان يتقلب",
    "hero.scroll": "انزل",
    "shop.eyebrow": "المنتجات",
    "shop.title": "اختار لمستك",
    "shop.lead": "كارت ليك، ستاند للكاشير، وكارت تستلم بيه فلوسك. ادفع مرة واحدة، والمس لسنين.",
    "shop.all": "الكل",
    "shop.cards": "كروت",
    "shop.stands": "ستاندات",
    "shop.view": "شوف",
    "shop.from": "من",
    "shop.page": "كل المتجر",
    "tag.new": "جديد",
    "tag.best": "الأكثر طلبًا",
    "prod.card": "كارت RemoTap",
    "prod.stand": "ستاند RemoTap",
    "prod.card.short": "كارت NFC أسود بيشارك صفحتك بلمسة.",
    "prod.stand.short": "ستاند للكاشير: العميل يلمس يدفع أو يتابع أو يقيّم.",
    "prod.plan": "الباقة",
    "prod.qty": "الكمية",
    "prod.design": "شكل الكارت",
    "prod.design.note": "اختار الشكل اللي يعجبك. هنبعتلك التصميم النهائي على واتساب قبل الطباعة.",
    "prod.flip": "اقلب الكارت",
    "prod.shuffle": "شكل تاني",
    "prod.get": "هتاخد إيه",
    "prod.delivery": "التوصيل والدفع",
    "prod.delivery.b": "بنصنعه مخصوص في ٤–٧ أيام ونوصّله لأي مكان في القاهرة والجيزة. مصاريف الشحن بتتضاف عند الطلب. الدفع بإنستاباي بعد الطلب.",
    "prod.back": "كل المنتجات",
    "prod.other": "ممكن يعجبك كمان",
    "stand.tap": "المس وادفع",
    "stand.scan": "أو امسح",
    "cart.title": "سلتك",
    "cart.empty": "السلة فاضية.",
    "cart.empty.cta": "روح للمتجر",
    "cart.add": "ضيف للسلة",
    "cart.added": "اتضاف للسلة",
    "cart.buy": "اشتري دلوقتي",
    "cart.remove": "شيل",
    "cart.sub": "المجموع",
    "cart.delnote": "مصاريف الشحن بتتضاف عند الطلب.",
    "cart.checkout": "كمّل الطلب",
    "cart.keep": "كمّل تسوق",
    "cart.count": "{n} منتجات",
    "o.s1.t": "سلتك",
    "o.s1.l": "راجع منتجاتك. تقدر تضيف منتج تاني أو تغيّر الكمية.",
    "o.addmore": "ضيف منتج تاني",
    "o.empty": "السلة فاضية. ضيف منتج عشان تكمّل.",
    "o.oneperorder": "كل المنتجات في الطلب ده بتفتح نفس الصفحة.",
    "o.design": "الشكل",
    "p.items": "المنتجات",
    "p.wamsg2": "أهلاً RemoTap! عملت طلب رقم {id}.\n{items}\nالإجمالي: {total} جنيه\nالاسم: {name}\nمرفق صورة تحويل إنستاباي.",
    "foot.shop": "المتجر",
    "foot.help": "مساعدة",
    "foot.follow": "كلّمنا",
    "foot.drops": "اعرف المنتجات والعروض الجديدة على واتساب",
    "foot.drops.btn": "اشترك على واتساب",
    "foot.drops.msg": "أهلاً RemoTap! ضيفوني على قائمة التحديثات.",
    "demo.phone.save": "احفظ الرقم",
    "demo.phone.resume": "شوف السيرة الذاتية",
    "big.1": "من غير أبلكيشن.",
    "big.2": "من غير كتابة.",
    "big.3": "المس وبس.",
  },
};

export type Lang = "en" | "ar";
export const DICT: Record<Lang, Record<string, string>> = {
  en: { ...BASE.en, ...EXTRA.en },
  ar: { ...BASE.ar, ...EXTRA.ar },
};
